import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const FAQ = () => {
  const faqs = [
    {
      question: "How does AI Reactor create viral content?",
      answer: "AI Reactor uses advanced machine learning algorithms to analyze viral patterns, trending topics, and user engagement data across all major platforms. Our AI then generates scripts, visuals, and optimizes content timing to maximize viral potential."
    },
    {
      question: "Which platforms does AI Reactor support?",
      answer: "AI Reactor supports all major short-form video platforms including TikTok, YouTube Shorts, Instagram Reels, X (Twitter), and LinkedIn. Content is automatically optimized for each platform's specific requirements and audience preferences."
    },
    {
      question: "How long does it take to see results?",
      answer: "Most users see their first viral video within 24-48 hours of setup. Our AI learns from your audience and continuously improves performance, with significant growth typically visible within the first week."
    },
    {
      question: "Do I need any technical skills to use AI Reactor?",
      answer: "No technical skills required! AI Reactor is designed to be completely automated. Simply connect your social media accounts, set your preferences, and our AI handles everything from content creation to publishing."
    },
    {
      question: "Can I customize the content AI Reactor creates?",
      answer: "Yes! While AI Reactor works autonomously, you can set brand guidelines, content themes, posting schedules, and approval workflows. You maintain full control over your brand voice and messaging."
    },
    {
      question: "Is my content original and safe from copyright issues?",
      answer: "Absolutely. All content generated by AI Reactor is 100% original, created from scratch by our AI models. We also include advanced copyright checking and brand safety measures to protect your accounts."
    },
    {
      question: "How much does AI Reactor cost?",
      answer: "We offer flexible pricing plans starting from $99/month for individual creators up to enterprise solutions for agencies and large brands. All plans include unlimited content generation and multi-platform publishing."
    },
    {
      question: "Can I cancel anytime?",
      answer: "Yes, you can cancel your subscription at any time with no long-term commitments. Your account will remain active until the end of your current billing period."
    }
  ];

  return (
    <section id="faq" className="py-24 px-6 bg-gradient-subtle">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-5xl md:text-6xl font-bold font-orbitron mb-6">
            <span className="bg-gradient-primary bg-clip-text text-transparent">
              FREQUENTLY ASKED
            </span>
            <br />
            <span className="text-foreground">QUESTIONS</span>
          </h2>
          <p className="text-xl text-muted-foreground font-inter">
            Everything you need to know about AI Reactor
          </p>
        </div>

        <Accordion type="single" collapsible className="space-y-4">
          {faqs.map((faq, index) => (
            <AccordionItem 
              key={index} 
              value={`item-${index}`}
              className="border border-primary/20 rounded-lg px-6 bg-card/30 hover:border-primary/40 transition-all duration-300"
            >
              <AccordionTrigger className="text-left font-orbitron font-semibold text-lg hover:text-primary">
                {faq.question}
              </AccordionTrigger>
              <AccordionContent className="text-muted-foreground font-inter leading-relaxed pt-2">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>

        <div className="mt-12 text-center">
          <p className="text-muted-foreground font-inter">
            Have more questions? 
            <a href="#contact" className="text-primary hover:text-accent transition-colors ml-1 font-semibold">
              Get in touch with our team
            </a>
          </p>
        </div>
      </div>
    </section>
  );
};

export default FAQ;