// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnoouwzrddsbyhjmjbdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdub291d3pyZGRzYnloam1qYmR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NzI0ODcsImV4cCI6MjA2ODA0ODQ4N30.jjf4Z4Fx7ehwh_i9O_QlO-a1eQcsaZXtbHEFs4DCijI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});